services:
  mongodb:
    image: mongo:5.0.6
    container_name: mongodb
    restart: unless-stopped
    hostname: test_mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD
      - MONGO_INITDB_DATABASE
      - MONGODB_DATA_DIR
      - MONGODB_LOG_DIR
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"

  main:
    build: .
    container_name: main
    restart: unless-stopped
    environment:
      - MONGODB_DATABASE
      - MONGODB_USERNAME
      - MONGODB_PASSWORD
      - MONGODB_HOSTNAME
    volumes:
      - files_data:/home/CLaaS_Server/files
      - datasets:/home/CLaaS_Server/common
    depends_on:
      - mongodb
    ports:
      - "5000:5000"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

volumes:
  mongodb_data:
    name: mongodb_data
    external: true
  files_data:
    name: files_data
    external: true
  datasets:
    name: datasets
    external: true